version: '3.7'

services:
  web:
    build: .
    # command: python manage.py run -h 0.0.0.0
    # volumes:
    #   - ./services/web/:/usr/src/app/
    # ports:
    #   - 5000:5000
    # env_file:
    #   - ./.env.dev

#docker-compose build
#docker-compose up -d
#docker run -t -i ubuntu /bin/bash(if install bash,if not please thing other way to open docker)